### PR TITLE
Improve debian-cross CI scripts

### PR DESCRIPTION
**Pull request by lumag**
cc @krzk

### CODE REVIEW

**Comment by krzk** [comment]
It seems I cannot provide here review +1..., so old fashioned way:

Reviewed-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>

**Comment by krzk** [comment]
Thanks, I ported them also to neard (which I used as a base for this CI).

**Comment by krzk** [comment]
Anything happening here?

**Review by krzk — APPROVED** [review]

**Review by konradybcio — APPROVED** [review]
lgtm

**Pull request merged**
